apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: python:3.11-slim
          workingDir: /app
          command: ["/bin/sh", "-c"]
          args:
            - "pip install --no-cache-dir fastapi==0.111.0 'uvicorn[standard]==0.30.1' && uvicorn main:app --host 0.0.0.0 --port 8000"
          ports:
            - containerPort: 8000
          env:
            - name: VERSION
              value: "v1"
            - name: ERROR_RATE
              value: "0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: web-config
          volumeMounts:
            - name: code
              mountPath: /app/main.py
              subPath: main.py
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      volumes:
        - name: code
          configMap:
            name: backend-code
  strategy:
    canary:
      stableService: backend
      canaryService: backend-canary
      steps:
        - setWeight: 25
        - pause:
            duration: 1m
        - setWeight: 50
        - pause:
            duration: 1m
        - setWeight: 100
      analysis:
        templates:
          - templateName: success-rate-analysis
        startingStep: 1
        args:
          - name: namespace
            value: demo
