apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-analysis
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  args:
    - name: namespace
  metrics:
    - name: success-rate
      # Chạy mỗi 30 giây, thực hiện 3 lần đo
      interval: 30s
      count: 3
      # Cho phép tối đa 1 lần đo thất bại
      failureLimit: 1
      # SLO: success rate >= 95%
      successCondition: result[0] >= 0.95
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring:9090
          query: |
            sum(rate(flask_http_request_total{namespace="{{args.namespace}}",status!~"5.."}[2m]))
            /
            sum(rate(flask_http_request_total{namespace="{{args.namespace}}"}[2m]))
