apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nhatphanhk/gitops.git
    path: k8s-api
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    # Argo Rollouts tự quản lý selector của api-canary service
    - group: ""
      kind: Service
      name: api-canary
      namespace: demo
      jsonPointers:
        - /spec/selector
    # Rollout status thường có diff do managed fields
    - group: argoproj.io
      kind: Rollout
      name: api
      namespace: demo
      jsonPointers:
        - /spec/template/metadata/annotations
