apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nhatphanhk/gitops.git
    path: k8s/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    # Argo Rollouts tự quản lý selector của backend-canary service
    - group: ""
      kind: Service
      name: backend-canary
      namespace: demo
      jsonPointers:
        - /spec/selector
    # rollouts-controller thêm analysisRunMetadata và các fields vào Rollout
    - group: argoproj.io
      kind: Rollout
      namespace: demo
      jqPathExpressions:
        - .spec.strategy.canary.analysis.analysisRunMetadata
      managedFieldsManagers:
        - rollouts-controller
