apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
            serviceMonitorSelector: {}
            ruleNamespaceSelector: {}
            ruleSelector: {}

        grafana:
          adminPassword: "admin"

        alertmanager:
          enabled: false
          config:
            global:
              resolve_timeout: 5m
              smtp_smarthost: "smtp.gmail.com:587"
              smtp_from: "Nhatphanhk102@gmail.com"
              smtp_auth_username: "Nhatphanhk102@gmail.com"
              smtp_auth_password: "zkqr lvss jzhu doal"
              smtp_require_tls: true

            route:
              group_by: ["alertname", "namespace"]
              group_wait: 10s
              group_interval: 5m
              repeat_interval: 1h
              receiver: "email-alert"

            receivers:
              - name: "email-alert"
                email_configs:
                  - to: "nhatph102.work@gmail.com"
                    send_resolved: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true